site_name: Fine-Tuning Methods Documentation
site_description: A technical reference for LoRA, QLoRA, and other fine-tuning techniques.
site_author: Saurabh Goyal
repo_url: https://github.com/saurabhiit2007/LLM-Finetuning
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - mathjax
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: deep purple
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: lime
  font:
    text: Inter
    code: JetBrains Mono

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - PEFT Techniques:
      - Prefix Tuning: ./finetuning_techniques/prefix_tuning.md
      - LoRA: ./finetuning_techniques/lora.md
      - QLoRA: ./finetuning_techniques/qlora.md
      #- PEFT Overview: ./finetuning_techniques/peft.md
      #- Adapter Methods: ./finetuning_techniques/adapters.md
  - Supporting Topics:
      - 4-bit NormalFloat (NF4): ./supporting_topics/4bit_normal_float.md
      - Block-wise k-bit Quantization: ./supporting_topics/blockwise_kbit_quantization.md
      - Accelerate Framework: ./advanced_topics/accelerate.md
  - References: references.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - footnotes
  - tables
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.magiclink
